"""Zero Trust Policy Decision Point (PDP) for HNX26EPS01 Security Gateway.

Combines Role-Based Access Control (RBAC) and Attribute-Based Access Control (ABAC).
Evaluates identity, device identity, token binding, security posture, risk score,
and upstream workload identity before every request.

Enforces:
- Never Trust, Always Verify
- Default Deny
- Policy Versioning and Cryptographic Policy Hashing
- Explainable Reason Codes
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

import yaml

from core.client_registry import ClientRegistration
from core.identity import AuthenticatedPrincipal
from core.security_context import PostureState, RequestContext


@dataclass(frozen=True)
class PolicyRule:
    """RBAC + ABAC declarative policy rule specification."""

    id: str
    principal_role: str
    resource: str
    action: str  # "READ", "WRITE", "QUERY", "REVIEW", "ADMIN", "ANY"
    decision: str = "ALLOW"
    mtls_required: bool = True
    token_required: bool = True
    token_binding_required: bool = True
    step_up_required: bool = False
    allowed_postures: List[str] = field(default_factory=lambda: ["HEALTHY", "DEGRADED"])
    max_risk_score: int = 50
    required_scopes: List[str] = field(default_factory=list)

    def matches_resource(self, request_resource: str) -> bool:
        if self.resource == "*":
            return True
        if self.resource.endswith("*"):
            prefix = self.resource[:-1]
            return request_resource.startswith(prefix)
        return self.resource == request_resource

    def matches_action(self, request_action: str) -> bool:
        if self.action in ("ANY", "*"):
            return True
        return self.action.upper() == request_action.upper()


@dataclass(frozen=True)
class PolicyDecision:
    """Immutable, explainable policy decision generated by the PDP."""

    decision: str  # "ALLOW", "DENY", "STEP_UP", "REVIEW"
    policy_id: str
    policy_version: str
    policy_hash: str
    reason_codes: List[str]
    risk_score: int
    details: Dict[str, Any] = field(default_factory=dict)

    def is_allowed(self) -> bool:
        return self.decision == "ALLOW"


class ZeroTrustPolicyEngine:
    """Central Policy Decision Point (PDP) evaluating all Zero Trust vectors."""

    def __init__(self, config_path: Optional[str] = None, policy_dict: Optional[Dict[str, Any]] = None):
        self.policy_version = "2.0.0-zt"
        self.rules: List[PolicyRule] = []
        self.default_decision = "DENY"
        self.policy_hash = ""

        if policy_dict:
            self._load_from_dict(policy_dict)
        elif config_path:
            self.load_from_file(config_path)

    def load_from_file(self, config_path: str) -> None:
        path = Path(config_path).resolve()
        if not path.exists():
            raise FileNotFoundError(f"Zero trust policy file not found: {path}")

        raw_bytes = path.read_bytes()
        self.policy_hash = hashlib.sha256(raw_bytes).hexdigest()[:16]

        with open(path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)

        if not isinstance(data, dict):
            raise ValueError("Zero trust policy root must be a YAML dictionary")

        self._load_from_dict(data)

    def _load_from_dict(self, data: Dict[str, Any]) -> None:
        self.policy_version = str(data.get("policy_version", "2.0.0-zt"))
        self.default_decision = str(data.get("defaults", {}).get("decision", "DENY")).upper()

        if not self.policy_hash:
            canonical = json.dumps(data, sort_keys=True).encode("utf-8")
            self.policy_hash = hashlib.sha256(canonical).hexdigest()[:16]

        raw_policies = data.get("policies", [])
        self.rules.clear()

        for p in raw_policies:
            auth_spec = p.get("authentication", {})
            rule = PolicyRule(
                id=p.get("id", "unnamed-rule"),
                principal_role=p.get("principal_role", "ROLE_ANONYMOUS"),
                resource=p.get("resource", ""),
                action=p.get("action", "READ"),
                decision=p.get("decision", "ALLOW").upper(),
                mtls_required=bool(auth_spec.get("mtls", True)),
                token_required=bool(auth_spec.get("token", True)),
                token_binding_required=bool(auth_spec.get("token_binding", True)),
                step_up_required=bool(auth_spec.get("step_up", False)),
                allowed_postures=p.get("security_posture", {}).get("allowed", ["HEALTHY", "DEGRADED"]),
                max_risk_score=int(p.get("max_risk_score", 50)),
                required_scopes=list(p.get("required_scopes", [])),
            )
            self.rules.append(rule)

    def evaluate(
        self,
        ctx: RequestContext,
        client_reg: Optional[ClientRegistration],
        is_upstream_valid: bool = True,
    ) -> PolicyDecision:
        """Evaluates inbound RequestContext against continuous trust signals and policy rules.

        Fails closed with explainable reason codes.
        """
        # 1. Continuous Security Posture Evaluation
        if ctx.posture in (PostureState.LOCKDOWN, PostureState.COMPROMISED):
            reason = "WATCHDOG_ALERT" if ctx.posture == PostureState.LOCKDOWN else "INTEGRITY_COMPROMISED"
            return PolicyDecision(
                decision="DENY",
                policy_id="posture-enforcement",
                policy_version=self.policy_version,
                policy_hash=self.policy_hash,
                reason_codes=[reason, "SECURITY_POSTURE_UNHEALTHY"],
                risk_score=ctx.risk_score,
                details={"posture": ctx.posture.value},
            )

        # 2. Upstream Workload Identity Evaluation
        if not is_upstream_valid:
            return PolicyDecision(
                decision="DENY",
                policy_id="workload-enforcement",
                policy_version=self.policy_version,
                policy_hash=self.policy_hash,
                reason_codes=["UPSTREAM_IDENTITY_MISMATCH"],
                risk_score=ctx.risk_score,
                details={"error": "Upstream process does not match expected workload identity"},
            )

        # 3. Principal Identity & Device Verification
        principal = ctx.principal
        if not principal or not principal.principal_id or principal.principal_id.startswith("anonymous"):
            return PolicyDecision(
                decision="DENY",
                policy_id="identity-enforcement",
                policy_version=self.policy_version,
                policy_hash=self.policy_hash,
                reason_codes=["IDENTITY_UNKNOWN"],
                risk_score=ctx.risk_score,
            )

        # 4. Device Registration Verification
        if not client_reg:
            return PolicyDecision(
                decision="DENY",
                policy_id="device-enforcement",
                policy_version=self.policy_version,
                policy_hash=self.policy_hash,
                reason_codes=["DEVICE_NOT_REGISTERED"],
                risk_score=ctx.risk_score,
                details={"cert_fingerprint": principal.certificate_fingerprint},
            )

        is_dev_active, dev_reason = client_reg.is_valid_and_active()
        if not is_dev_active:
            return PolicyDecision(
                decision="DENY",
                policy_id="device-enforcement",
                policy_version=self.policy_version,
                policy_hash=self.policy_hash,
                reason_codes=[dev_reason],
                risk_score=ctx.risk_score,
            )

        # 5. Token-to-Certificate Binding Verification
        if principal.certificate_fingerprint:
            if not principal.binds_to_certificate(client_reg.certificate_sha256):
                return PolicyDecision(
                    decision="DENY",
                    policy_id="binding-enforcement",
                    policy_version=self.policy_version,
                    policy_hash=self.policy_hash,
                    reason_codes=["TOKEN_BINDING_MISMATCH"],
                    risk_score=ctx.risk_score,
                    details={"token_cert": principal.certificate_fingerprint, "device_cert": client_reg.certificate_sha256},
                )

        # 6. Critical Risk Score Gate
        if ctx.risk_score > 75:
            return PolicyDecision(
                decision="DENY",
                policy_id="risk-gate",
                policy_version=self.policy_version,
                policy_hash=self.policy_hash,
                reason_codes=["RISK_TOO_HIGH"],
                risk_score=ctx.risk_score,
                details={"score": ctx.risk_score},
            )

        # 7. Match RBAC + ABAC Rules
        for rule in self.rules:
            if rule.principal_role != principal.role:
                continue
            if not rule.matches_resource(ctx.resource):
                continue
            if not rule.matches_action(ctx.action):
                continue

            # Context Attribute: Security Posture
            if ctx.posture.value not in rule.allowed_postures:
                return PolicyDecision(
                    decision="DENY",
                    policy_id=rule.id,
                    policy_version=self.policy_version,
                    policy_hash=self.policy_hash,
                    reason_codes=["HOST_POSTURE_RESTRICTED"],
                    risk_score=ctx.risk_score,
                    details={"current_posture": ctx.posture.value, "allowed": rule.allowed_postures},
                )

            # Context Attribute: Risk Threshold
            if ctx.risk_score > rule.max_risk_score:
                return PolicyDecision(
                    decision="DENY",
                    policy_id=rule.id,
                    policy_version=self.policy_version,
                    policy_hash=self.policy_hash,
                    reason_codes=["RISK_TOO_HIGH_FOR_ACTION"],
                    risk_score=ctx.risk_score,
                    details={"score": ctx.risk_score, "limit": rule.max_risk_score},
                )

            # Context Attribute: Scopes
            if rule.required_scopes:
                missing = [s for s in rule.required_scopes if not principal.has_scope(s)]
                if missing:
                    return PolicyDecision(
                        decision="DENY",
                        policy_id=rule.id,
                        policy_version=self.policy_version,
                        policy_hash=self.policy_hash,
                        reason_codes=["SCOPE_NOT_PERMITTED"],
                        risk_score=ctx.risk_score,
                        details={"missing_scopes": missing},
                    )

            # Context Attribute: Step-Up Authentication
            if rule.step_up_required and not principal.step_up_verified:
                return PolicyDecision(
                    decision="STEP_UP",
                    policy_id=rule.id,
                    policy_version=self.policy_version,
                    policy_hash=self.policy_hash,
                    reason_codes=["STEP_UP_AUTHENTICATION_REQUIRED"],
                    risk_score=ctx.risk_score,
                    details={"resource": ctx.resource},
                )

            # Matched rule decision
            return PolicyDecision(
                decision=rule.decision,
                policy_id=rule.id,
                policy_version=self.policy_version,
                policy_hash=self.policy_hash,
                reason_codes=["POLICY_MATCH_ALLOWED"] if rule.decision == "ALLOW" else ["POLICY_RULE_DENY"],
                risk_score=ctx.risk_score,
            )

        # 8. Fail Closed: Default Deny
        return PolicyDecision(
            decision="DENY",
            policy_id="default-deny",
            policy_version=self.policy_version,
            policy_hash=self.policy_hash,
            reason_codes=["POLICY_DEFAULT_DENY", "RESOURCE_NOT_ALLOWED"],
            risk_score=ctx.risk_score,
            details={"role": principal.role, "resource": ctx.resource, "action": ctx.action},
        )
